import xuance
"""
报错：
numpy.core._exceptions.MemoryError: Unable to allocate 4.29 GiB for an array with shape (1, 1601, 3, 400, 600) and data type float32
"""

# 按装订区域中的绿色按钮以运行脚本。
if __name__ == '__main__':
    print("ERROR")
    # runner = xuance.get_runner(method='td3',
    #                            env='box2d',
    #                            env_id='BipedalWalker-v3',
    #                            is_test=True)
    # runner.run()

